name = "MultiFloatLinearAlgebra"
uuid = "642d9d30-8e28-45ca-9d81-256429ea358f"
authors = ["Yongjun Xu", "David K. Zhang"]
version = "0.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultiFloats = "bdf0d083-296b-4888-a5b6-7498122e68a5"

[weakdeps]
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[extensions]
MultiFloatLinearSolveExt = ["LinearSolve", "SciMLBase"]

[compat]
Aqua = "0.8"
LinearAlgebra = "1"
LinearSolve = "2.22, 3.83, 4, 5"
MultiFloats = "3.2"
Random = "1"
SciMLBase = "2, 3"
Test = "1"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "LinearSolve", "Random", "SciMLBase", "Test"]
